export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";

const JAKARTA_UTC_OFFSET_HOURS = 7;
const DEFAULT_WORKING_DAYS = [
  "MONDAY",
  "TUESDAY",
  "WEDNESDAY",
  "THURSDAY",
  "FRIDAY",
];
const WEEKDAY_MAP = [
  "SUNDAY",
  "MONDAY",
  "TUESDAY",
  "WEDNESDAY",
  "THURSDAY",
  "FRIDAY",
  "SATURDAY",
] as const;

function isAuthorizedCron(req: NextRequest) {
  const cronSecret = process.env.CRON_SECRET;
  if (!cronSecret) return true;
  const authHeader = req.headers.get("authorization") || "";
  return authHeader === `Bearer ${cronSecret}`;
}

function getPreviousJakartaDayRange(nowUtc = new Date()) {
  const shifted = new Date(
    nowUtc.getTime() + JAKARTA_UTC_OFFSET_HOURS * 60 * 60 * 1000,
  );

  const y = shifted.getUTCFullYear();
  const m = shifted.getUTCMonth();
  const d = shifted.getUTCDate() - 1;

  const startUtc = new Date(
    Date.UTC(y, m, d, -JAKARTA_UTC_OFFSET_HOURS, 0, 0, 0),
  );
  const endUtc = new Date(
    Date.UTC(y, m, d, 23 - JAKARTA_UTC_OFFSET_HOURS, 59, 59, 999),
  );

  return { startUtc, endUtc };
}

export async function GET(req: NextRequest) {
  try {
    if (!isAuthorizedCron(req)) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const { startUtc, endUtc } = getPreviousJakartaDayRange();
    const targetDayCode = WEEKDAY_MAP[
      new Date(
        startUtc.getTime() + JAKARTA_UTC_OFFSET_HOURS * 60 * 60 * 1000,
      ).getUTCDay()
    ];

    const eligibleUsers = await prisma.user.findMany({
      where: {
        status: "active",
        deletedAt: null,
        AND: [
          {
            OR: [{ joinDate: null }, { joinDate: { lte: endUtc } }],
          },
          {
            OR: [
              { tenantId: null },
              {
                tenant: {
                  isActive: true,
                },
              },
            ],
          },
        ],
      },
      select: {
        id: true,
        tenantId: true,
      },
    });

    if (eligibleUsers.length === 0) {
      return NextResponse.json({
        message: "Attendance absent job completed",
        created: 0,
        targetDateStart: startUtc.toISOString(),
        targetDateEnd: endUtc.toISOString(),
      });
    }

    const tenantIds = [...new Set(eligibleUsers.map((u: any) => u.tenantId).filter(Boolean))] as string[];
    const configs = await prisma.attendanceConfig.findMany({
      where: {
        OR: [
          { tenantId: { in: tenantIds } },
          { tenantId: null },
        ],
      },
      orderBy: {
        updatedAt: "desc",
      },
      select: {
        tenantId: true,
        workingDays: true,
      },
    });

    const configByTenant = new Map<string, string[]>();
    let globalConfigWorkingDays: string[] | null = null;
    for (const cfg of configs) {
      const normalizedDays =
        Array.isArray(cfg.workingDays) && cfg.workingDays.length > 0
          ? cfg.workingDays
          : DEFAULT_WORKING_DAYS;

      if (cfg.tenantId) {
        if (!configByTenant.has(cfg.tenantId)) {
          configByTenant.set(cfg.tenantId, normalizedDays);
        }
        continue;
      }

      if (!globalConfigWorkingDays) {
        globalConfigWorkingDays = normalizedDays;
      }
    }

    const usersToProcess = eligibleUsers.filter((user: any) => {
      const workingDays =
        (user.tenantId ? configByTenant.get(user.tenantId) : null) ||
        globalConfigWorkingDays ||
        DEFAULT_WORKING_DAYS;
      return workingDays.includes(targetDayCode);
    });

    if (usersToProcess.length === 0) {
      return NextResponse.json({
        message: "Attendance absent job completed",
        created: 0,
        targetDateStart: startUtc.toISOString(),
        targetDateEnd: endUtc.toISOString(),
        checkedUsers: eligibleUsers.length,
        skippedByWorkingDay: eligibleUsers.length,
        targetDayCode,
      });
    }

    const existingAttendances = await prisma.attendance.findMany({
      where: {
        date: {
          gte: startUtc,
          lte: endUtc,
        },
        userId: {
          in: usersToProcess.map((u) => u.id),
        },
      },
      select: {
        userId: true,
      },
    });

    const existingUserIds = new Set(existingAttendances.map((a: any) => a.userId));
    const attendanceToCreate = usersToProcess
      .filter((u: any) => !existingUserIds.has(u.id))
      .map((u: any) => ({
        userId: u.id,
        tenantId: u.tenantId ?? null,
        date: startUtc,
        status: "Absent",
        notes: "Auto generated by cron",
        workHours: "00:00",
      }));

    if (attendanceToCreate.length > 0) {
      await prisma.attendance.createMany({
        data: attendanceToCreate,
        skipDuplicates: true,
      });
    }

    return NextResponse.json({
      message: "Attendance absent job completed",
      created: attendanceToCreate.length,
      targetDateStart: startUtc.toISOString(),
      targetDateEnd: endUtc.toISOString(),
      checkedUsers: usersToProcess.length,
      skippedByWorkingDay: eligibleUsers.length - usersToProcess.length,
      targetDayCode,
    });
  } catch (error) {
    console.error("CRON ATTENDANCE ABSENT ERROR:", error);
    return NextResponse.json(
      { message: "Failed to run attendance absent job" },
      { status: 500 },
    );
  }
}