export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";

const JAKARTA_UTC_OFFSET_HOURS = 7;

function isAuthorizedCron(req: NextRequest) {
  const cronSecret = process.env.CRON_SECRET;
  if (!cronSecret) return true;
  const authHeader = req.headers.get("authorization") || "";
  return authHeader === `Bearer ${cronSecret}`;
}

function getPreviousJakartaDayRange(nowUtc = new Date()) {
  const shifted = new Date(
    nowUtc.getTime() + JAKARTA_UTC_OFFSET_HOURS * 60 * 60 * 1000,
  );

  const y = shifted.getUTCFullYear();
  const m = shifted.getUTCMonth();
  const d = shifted.getUTCDate() - 1;

  const startUtc = new Date(
    Date.UTC(y, m, d, -JAKARTA_UTC_OFFSET_HOURS, 0, 0, 0),
  );
  const endUtc = new Date(
    Date.UTC(y, m, d, 23 - JAKARTA_UTC_OFFSET_HOURS, 59, 59, 999),
  );

  return { startUtc, endUtc };
}

export async function GET(req: NextRequest) {
  try {
    if (!isAuthorizedCron(req)) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const { startUtc, endUtc } = getPreviousJakartaDayRange();

    const eligibleUsers = await prisma.user.findMany({
      where: {
        status: "active",
        deletedAt: null,
        AND: [
          {
            OR: [{ joinDate: null }, { joinDate: { lte: endUtc } }],
          },
          {
            OR: [
              { tenantId: null },
              {
                tenant: {
                  isActive: true,
                },
              },
            ],
          },
        ],
      },
      select: {
        id: true,
        tenantId: true,
      },
    });

    if (eligibleUsers.length === 0) {
      return NextResponse.json({
        message: "Attendance absent job completed",
        created: 0,
        targetDateStart: startUtc.toISOString(),
        targetDateEnd: endUtc.toISOString(),
      });
    }

    const existingAttendances = await prisma.attendance.findMany({
      where: {
        date: {
          gte: startUtc,
          lte: endUtc,
        },
        userId: {
          in: eligibleUsers.map((u) => u.id),
        },
      },
      select: {
        userId: true,
      },
    });

    const existingUserIds = new Set(existingAttendances.map((a) => a.userId));
    const attendanceToCreate = eligibleUsers
      .filter((u) => !existingUserIds.has(u.id))
      .map((u) => ({
        userId: u.id,
        tenantId: u.tenantId ?? null,
        date: startUtc,
        status: "Absent",
        notes: "Auto generated by cron",
        workHours: "00:00",
      }));

    if (attendanceToCreate.length > 0) {
      await prisma.attendance.createMany({
        data: attendanceToCreate,
      });
    }

    return NextResponse.json({
      message: "Attendance absent job completed",
      created: attendanceToCreate.length,
      targetDateStart: startUtc.toISOString(),
      targetDateEnd: endUtc.toISOString(),
      checkedUsers: eligibleUsers.length,
    });
  } catch (error) {
    console.error("CRON ATTENDANCE ABSENT ERROR:", error);
    return NextResponse.json(
      { message: "Failed to run attendance absent job" },
      { status: 500 },
    );
  }
}
