import prisma from "@/lib/prisma";
import { addDays, getJakartaDayKey } from "@/lib/helper/date";

export const AUTO_ABSENT_NOTE = "Auto generated by cron";
export const AUTO_SUBMISSION_ATTENDANCE_NOTE =
  "Auto generated by cron from approved submission";

function getCoveredAttendanceDays(startDate: Date, endDate: Date) {
  const startDay = getJakartaDayKey(startDate);
  const endDay = getJakartaDayKey(endDate);
  const days: Date[] = [];

  for (let day = startDay; day <= endDay; day = addDays(day, 1)) {
    days.push(day);
  }

  return days;
}

function isAutoGeneratedAttendance(notes?: string | null) {
  return (
    notes === AUTO_ABSENT_NOTE ||
    notes === AUTO_SUBMISSION_ATTENDANCE_NOTE
  );
}

export async function syncSubmissionAttendanceForRange({
  userId,
  tenantId,
  startDate,
  endDate,
}: {
  userId: string;
  tenantId?: string | null;
  startDate: Date;
  endDate: Date;
}) {
  const coveredDays = getCoveredAttendanceDays(startDate, endDate);
  const todayJakarta = getJakartaDayKey(new Date());
  const targetDays = coveredDays.filter((day) => day <= todayJakarta);

  if (targetDays.length === 0) {
    return;
  }

  const rangeStart = targetDays[0];
  const rangeEnd = targetDays[targetDays.length - 1];

  const [approvedSubmissions, existingAttendances] = await Promise.all([
    prisma.submission.findMany({
      where: {
        userId,
        ...(tenantId ? { tenantId } : {}),
        status: "APPROVED",
        startDate: {
          lte: endDate,
        },
        endDate: {
          gte: startDate,
        },
      },
      select: {
        id: true,
        startDate: true,
        endDate: true,
        approvedAt: true,
        createdAt: true,
        submissionType: {
          select: {
            name: true,
          },
        },
      },
      orderBy: [
        { approvedAt: "desc" },
        { createdAt: "desc" },
      ],
    }),
    prisma.attendance.findMany({
      where: {
        userId,
        ...(tenantId ? { tenantId } : {}),
        attendanceDay: {
          gte: rangeStart,
          lte: rangeEnd,
        },
      },
      select: {
        id: true,
        attendanceDay: true,
        checkIn: true,
        checkOut: true,
        notes: true,
        status: true,
      },
    }),
  ]);

  const existingAttendanceByDay = new Map(
    existingAttendances.map((attendance) => [
      attendance.attendanceDay.toISOString(),
      attendance,
    ]),
  );

  for (const day of targetDays) {
    const dayKey = day.toISOString();
    const matchingSubmission = approvedSubmissions.find((submission) => {
      const submissionStartDay = getJakartaDayKey(submission.startDate);
      const submissionEndDay = getJakartaDayKey(submission.endDate);
      return submissionStartDay <= day && submissionEndDay >= day;
    });

    const nextStatus = matchingSubmission?.submissionType.name ?? "Absent";
    const nextNotes = matchingSubmission
      ? AUTO_SUBMISSION_ATTENDANCE_NOTE
      : AUTO_ABSENT_NOTE;
    const existingAttendance = existingAttendanceByDay.get(dayKey);

    if (!existingAttendance) {
      await prisma.attendance.create({
        data: {
          userId,
          tenantId: tenantId ?? null,
          date: day,
          attendanceDay: day,
          status: nextStatus,
          notes: nextNotes,
          workHours: "00:00",
        },
      });
      continue;
    }

    if (
      existingAttendance.checkIn ||
      existingAttendance.checkOut ||
      !isAutoGeneratedAttendance(existingAttendance.notes)
    ) {
      continue;
    }

    if (
      existingAttendance.status === nextStatus &&
      existingAttendance.notes === nextNotes
    ) {
      continue;
    }

    await prisma.attendance.update({
      where: { id: existingAttendance.id },
      data: {
        status: nextStatus,
        notes: nextNotes,
        workHours: existingAttendance.status === "Absent" ? "00:00" : undefined,
      },
    });
  }
}
